controller_frequency: 20.0
min_vel_x: 0.0
max_vel_x: 0.3
min_vel_theta: -1.5
max_vel_theta: 1.5
acc_lim_x: 0.5
acc_lim_theta: 3.2
sim_time: 1.0
vx_samples: 20
vtheta_samples: 40
xy_goal_tolerance: 0.05
yaw_goal_tolerance: 0.1
occdist_scale: 0.01
path_distance_bias: 32.0
goal_distance_bias: 24.0
